// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/panel-layout": {
    params: {};
  };
  "/interaction": {
    params: {};
  };
  "/list-detail": {
    params: {};
  };
  "/primitives": {
    params: {};
  };
  "/data-view": {
    params: {};
  };
  "/dialogs": {
    params: {};
  };
  "/layouts": {
    params: {};
  };
  "/forms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/panel-layout" | "/interaction" | "/list-detail" | "/primitives" | "/data-view" | "/dialogs" | "/layouts" | "/forms";
  };
  "routes/panel-layout.tsx": {
    id: "routes/panel-layout";
    page: "/panel-layout";
  };
  "routes/interaction.tsx": {
    id: "routes/interaction";
    page: "/interaction";
  };
  "routes/list-detail.tsx": {
    id: "routes/list-detail";
    page: "/list-detail";
  };
  "routes/primitives.tsx": {
    id: "routes/primitives";
    page: "/primitives";
  };
  "routes/data-view.tsx": {
    id: "routes/data-view";
    page: "/data-view";
  };
  "routes/dialogs.tsx": {
    id: "routes/dialogs";
    page: "/dialogs";
  };
  "routes/layouts.tsx": {
    id: "routes/layouts";
    page: "/layouts";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/forms.tsx": {
    id: "routes/forms";
    page: "/forms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/panel-layout": typeof import("./app/routes/panel-layout.tsx");
  "routes/interaction": typeof import("./app/routes/interaction.tsx");
  "routes/list-detail": typeof import("./app/routes/list-detail.tsx");
  "routes/primitives": typeof import("./app/routes/primitives.tsx");
  "routes/data-view": typeof import("./app/routes/data-view.tsx");
  "routes/dialogs": typeof import("./app/routes/dialogs.tsx");
  "routes/layouts": typeof import("./app/routes/layouts.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/forms": typeof import("./app/routes/forms.tsx");
};